
services:
  web:
    build: .
    ports:
      - "8080:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=lili
      - DB_PASSWORD=password
      - DB_NAME=uvWebpage

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: uvWebpage
      MYSQL_USER: lili
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
