CREATE TABLE IF NOT EXISTS UserInfo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CityUv (
    id INT AUTO_INCREMENT PRIMARY KEY,
    City VARCHAR(100) NOT NULL,
    `UV Index` FLOAT NOT NULL
);
